// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Chat This object represents a chat.
type Chat struct {
	FirstName *string  `json:"first_name,omitempty"`
	Id        int      `json:"id"`
	LastName  *string  `json:"last_name,omitempty"`
	Title     *string  `json:"title,omitempty"`
	Type      ChatType `json:"type"`
	Username  *string  `json:"username,omitempty"`
}

// ChatType defines model for ChatType.
type ChatType = interface{}

// Message This object represents a message.
type Message struct {
	// Chat This object represents a chat.
	Chat      Chat    `json:"chat"`
	Date      int     `json:"date"`
	MessageId int     `json:"message_id"`
	Text      *string `json:"text,omitempty"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Ok     bool                   `json:"ok"`
	Result map[string]interface{} `json:"result"`
}

// Update This object represents an incoming update. At most one of the optional parameters can be present in any given update.
type Update struct {
	// EditedMessage This object represents a message.
	EditedMessage *Message `json:"edited_message,omitempty"`

	// Message This object represents a message.
	Message  *Message `json:"message,omitempty"`
	UpdateId int      `json:"update_id"`
}

// UpdateType defines model for UpdateType.
type UpdateType = interface{}

// User This object represents a Telegram user or bot
type User struct {
	AddedToAttachmentMenu   *bool `json:"added_to_attachment_menu,omitempty"`
	CanJoinGroups           *bool `json:"can_join_groups,omitempty"`
	CanReadAllGroupMessages *bool `json:"can_read_all_group_messages,omitempty"`

	// FirstName User's or bot's first name
	FirstName string `json:"first_name"`

	// Id Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
	Id                    int     `json:"id"`
	IsBot                 bool    `json:"is_bot"`
	IsPremium             *bool   `json:"is_premium,omitempty"`
	LanguageCode          *string `json:"language_code,omitempty"`
	LastName              *string `json:"last_name,omitempty"`
	SupportsInlineQueries *bool   `json:"supports_inline_queries,omitempty"`
	Username              *string `json:"username,omitempty"`
}

// ResponseFieldOK ok field is present in all responses
type ResponseFieldOK struct {
	Ok bool `json:"ok"`
}

// Token defines model for token.
type Token = string

// PostBotTokenGetUpdatesJSONBody defines parameters for PostBotTokenGetUpdates.
type PostBotTokenGetUpdatesJSONBody struct {
	AllowedUpdates *[]UpdateType `json:"allowed_updates,omitempty"`
	Limit          *int          `json:"limit,omitempty"`
	Offset         *int          `json:"offset,omitempty"`
	Timeout        *int          `json:"timeout,omitempty"`
}

// PostBotTokenGetUpdatesJSONRequestBody defines body for PostBotTokenGetUpdates for application/json ContentType.
type PostBotTokenGetUpdatesJSONRequestBody PostBotTokenGetUpdatesJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBotTokenGetMe request
	GetBotTokenGetMe(ctx context.Context, token string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostBotTokenGetUpdatesWithBody request with any body
	PostBotTokenGetUpdatesWithBody(ctx context.Context, token Token, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostBotTokenGetUpdates(ctx context.Context, token Token, body PostBotTokenGetUpdatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBotTokenGetMe(ctx context.Context, token string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBotTokenGetMeRequest(c.Server, token)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBotTokenGetUpdatesWithBody(ctx context.Context, token Token, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBotTokenGetUpdatesRequestWithBody(c.Server, token, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBotTokenGetUpdates(ctx context.Context, token Token, body PostBotTokenGetUpdatesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBotTokenGetUpdatesRequest(c.Server, token, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBotTokenGetMeRequest generates requests for GetBotTokenGetMe
func NewGetBotTokenGetMeRequest(server string, token string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "token", runtime.ParamLocationPath, token)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot%s/getMe", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostBotTokenGetUpdatesRequest calls the generic PostBotTokenGetUpdates builder with application/json body
func NewPostBotTokenGetUpdatesRequest(server string, token Token, body PostBotTokenGetUpdatesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostBotTokenGetUpdatesRequestWithBody(server, token, "application/json", bodyReader)
}

// NewPostBotTokenGetUpdatesRequestWithBody generates requests for PostBotTokenGetUpdates with any type of body
func NewPostBotTokenGetUpdatesRequestWithBody(server string, token Token, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "token", runtime.ParamLocationPath, token)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bot%s/getUpdates", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBotTokenGetMeWithResponse request
	GetBotTokenGetMeWithResponse(ctx context.Context, token string, reqEditors ...RequestEditorFn) (*GetBotTokenGetMeResponse, error)

	// PostBotTokenGetUpdatesWithBodyWithResponse request with any body
	PostBotTokenGetUpdatesWithBodyWithResponse(ctx context.Context, token Token, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBotTokenGetUpdatesResponse, error)

	PostBotTokenGetUpdatesWithResponse(ctx context.Context, token Token, body PostBotTokenGetUpdatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBotTokenGetUpdatesResponse, error)
}

type GetBotTokenGetMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok bool `json:"ok"`

		// Result This object represents a Telegram user or bot
		Result User `json:"result"`
	}
}

// Status returns HTTPResponse.Status
func (r GetBotTokenGetMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBotTokenGetMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostBotTokenGetUpdatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok     bool     `json:"ok"`
		Result []Update `json:"result"`
	}
}

// Status returns HTTPResponse.Status
func (r PostBotTokenGetUpdatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBotTokenGetUpdatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetBotTokenGetMeWithResponse request returning *GetBotTokenGetMeResponse
func (c *ClientWithResponses) GetBotTokenGetMeWithResponse(ctx context.Context, token string, reqEditors ...RequestEditorFn) (*GetBotTokenGetMeResponse, error) {
	rsp, err := c.GetBotTokenGetMe(ctx, token, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBotTokenGetMeResponse(rsp)
}

// PostBotTokenGetUpdatesWithBodyWithResponse request with arbitrary body returning *PostBotTokenGetUpdatesResponse
func (c *ClientWithResponses) PostBotTokenGetUpdatesWithBodyWithResponse(ctx context.Context, token Token, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBotTokenGetUpdatesResponse, error) {
	rsp, err := c.PostBotTokenGetUpdatesWithBody(ctx, token, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBotTokenGetUpdatesResponse(rsp)
}

func (c *ClientWithResponses) PostBotTokenGetUpdatesWithResponse(ctx context.Context, token Token, body PostBotTokenGetUpdatesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBotTokenGetUpdatesResponse, error) {
	rsp, err := c.PostBotTokenGetUpdates(ctx, token, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBotTokenGetUpdatesResponse(rsp)
}

// ParseGetBotTokenGetMeResponse parses an HTTP response from a GetBotTokenGetMeWithResponse call
func ParseGetBotTokenGetMeResponse(rsp *http.Response) (*GetBotTokenGetMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBotTokenGetMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok bool `json:"ok"`

			// Result This object represents a Telegram user or bot
			Result User `json:"result"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostBotTokenGetUpdatesResponse parses an HTTP response from a PostBotTokenGetUpdatesWithResponse call
func ParsePostBotTokenGetUpdatesResponse(rsp *http.Response) (*PostBotTokenGetUpdatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBotTokenGetUpdatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok     bool     `json:"ok"`
			Result []Update `json:"result"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
